
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/auth/**
      - id: subscription-service
        uri: lb://subscription-service
        predicates:
        - Path=/api/**




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




server:
  port: 8060


logging:
  file:
    name: logs/your-application.log 
  level:
    com.example.subscription_service: DEBUG # Log your own service code
    org.springframework.web: DEBUG # Log web request handling
    org.springframework.security: DEBUG # Log Spring Security if you have it in Subscription Service
    org.springframework.data: DEBUG # Log Spring Data JPA if you are using it
    # Add other relevant packages for debugging


management:
  tracing:
    sampling:
      probability: 1.0


