
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/**




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




server:
  port: 8060


logging:
  level:
    org:
      springframework:
        security: INFO


management:
  tracing:
    sampling:
      probability: 1.0
